### ISSUE TITLE
Specify temp file location?

### ISSUE THREAD

**Issue by eam12** [insapathogenomics/ReporTree#18]
Hi,

Is there any way to specify the location of temp files created during the running of `reportree.py` (e.g. `temporary_clean_codes.tsv`, `temporary_profile.tsv`, `tmp_dist_hamming.tsv`, etc.)? I'm trying to run `reportree.py` concurrently on several datasets and find that the temp files for all runs are created in the same directory (the directory I ran the scripts from) leading to various errors. I can fix this by submitting each run from a different directory, but it would be nice if there was a way to designate the temp directory in the `reportree.py` script.

Thanks so much!

**Comment by vmixao** [comment]
Dear @eam12 

Thank you for pointing this out. We have fixed the issue by adding the output prefix to temporary profiles.

Cheers,
Verónica
