### ISSUE TITLE
Clarification on defining genetic clusters using partitioning_grapetree.py

### ISSUE THREAD

**Issue by eam12** [insapathogenomics/ReporTree#24]
Continuing to love using ReporTree! I do have a clarifying question regarding how genetic clusters are defined when using GrapeTree and MSTreeV2 (`--analysis grapetree --method MSTreeV2`). What is the specific algorithm used to cut the tree at the specified thresholds once the tree has been constructed? Is it the GrapeTree branch collapsing algorithm defined in the supplemental material of [Zhou et al. 2018](https://genome.cshlp.org/content/28/9/1395.full)? I'm trying to get a better sense of what's going on "behind the scenes" and am finding myself a bit confused as to the specifics of how partitions are defined. Any help would be greatly appreciated!

**Comment by vmixao** [comment]
Hi @eam12 

Thank you for your feedback. We are happy that ReporTree is useful for your work.

**We designed ReporTree to do exactly what the user would do manually when analyzing the tree: define genetic clusters based on the distance between the nodes**. This is why, if you use the *metadata_w_partitions.tsv to color the tree, you will see that there is a perfect match between them.

For this, we use our own script ([partitioning_grapetree.py](https://github.com/insapathogenomics/ReporTree/blob/main/scripts/partitioning_grapetree.py)), which, based on the distance between two connected nodes in the tree (and not on the sample distance matrix), determines if two nodes correspond to a cluster (i.e. are connected by a distance lower or equal to the defined threshold). Of note, we also recover information about the redundant samples removed by GrapeTree and, if there were any, we add them as members of the respective cluster.

Please let us know if this answers your doubts.

I take this chance to invite you to try the new features we have just released in v2.5.0 :)

Kind regards,
Verónica

**Comment by eam12** [comment]
Thank you very much! I think I understand now. And the benefit of this method over relying solely on the distance matrix would be that [partitioning_grapetree.py](https://github.com/insapathogenomics/ReporTree/blob/main/scripts/partitioning_grapetree.py) takes tree topology into account, correct?

**Comment by vmixao** [comment]
Just to clarify, ReporTree is not a method of clustering but of extracting clusters from a tree. GrapeTree calculates a distance matrix and then uses this information to produce a minimum spanning tree (clustering). ReporTree uses this tree to identify the clusters present in your dataset (according to the tree) at any (or all) distance threshold you request. With this, you do not need to spend much time visually analyzing your tree to infer the clusters. Instead, you can find all this information in a single table and already combining some characterization with metadata.

Thanks!

**Comment by eam12** [comment]
I see. I think the confusion came from instances where our trees look like the image below. Clusters are colored based on a threshold of 14. In this tree, some of the nodes in the dark blue cluster (cluster_83) are "closer" (based on combined branch lengths) to nodes in the orange cluster (cluster_69) than they are to some other cluster_83 nodes. For example, node A has a branch length to cluster_69 node B of 21 but a combined branch length to node C of 24 (12+12). I completely understand that cluster membership is based on branch lengths _directly_ between two nodes, but it can get a bit visually confusing in situations such as this! Thank you for your clarifications.
<img width="884" alt="Screen Shot 2024-07-26 at 10 22 42 AM" src="https://github.com/user-attachments/assets/f77be8ea-7b50-47af-9462-d5aa96007d71">

**Comment by vmixao** [comment]
I understand that this is a bit confusing but, actually, from a minimum spanning tree you can not infer the distance between nodes that are not directly connected with a line. I mean, indeed, the distance between A and B is 21, but the distance between A and C may not be 24. A is connected to an intermediate node by 12 differences, so they form a cluster (<= 14). Then this intermediate node is connected to C by 12, so the cluster is extended. This does not mean that the distance from A to C is 12 + 12. Actually, it is likely much less. You can confirm this in the sample distance matrix ReporTree provides.

**Comment by eam12** [comment]
My apologies! I completely forgot that aspect of MSTs. This has cleared up many things for me. Many, many thanks!
