### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by ginevrach** [insapathogenomics/ReporTree#29]
running the following command:
"docker pull insapathogenomics/reportree:v2" or "docker pull insapathogenomics/reportree"

getting the following message:
"Error response from daemon: manifest for insapathogenomics/reportree:v2 not found: manifest unknown: manifest unknown"
or 
"Using default tag: latest
Error response from daemon: manifest for insapathogenomics/reportree:latest not found: manifest unknown: manifest unknown"

**Comment by vmixao** [comment]
Hi @ginevrach 

Thanks for reporting this issue. By mistake we left the command for docker installation incomplete. We apologize for that. This has now been fixed.

The right command is:

```bash
docker pull insapathogenomics/reportree:v2.5.2
```

Thanks!
Verónica

**Comment by ginevrach** [comment]
Thank you, everything is perfect now
