### ISSUE TITLE
use sys.executable for inner python calls 

### ISSUE THREAD

**Issue by EricDeveaud** [insapathogenomics/ReporTree#4]
Hello, 

hardcoding Python to 'python' for the innsercalls performed by reportree.py may cause problems

lets illustrate it
given the following script

```
#!/usr/bin/env python
import sys
print('runnig with:', sys.executable)
``
now run it 
```
rpm_maker:home/gensoft > ./tt.py 
runnig /usr/bin/python3
rpm_maker:home/gensoft > module load Python/3.8.1
rpm_maker:home/gensoft > ./tt.py 
runnig /opt/gensoft/exe/Python/3.8.1/bin/python3
```
thus if we go back to `reportree.py` using hardcoded `python` one can have a different python used, on for running the script while inner calls are performed with python from the path
while using `sys.executable` instead of hardcoded `python` ensure that all the inner calls are performed with the same interpreter than the onethe script is run with.

regards

Eric

**Comment by vmixao** [comment]
Hi Eric

Thanks for the tip. This has been modified in the commit c6c54ad3a1007f9d8f5118e5c888e67165c3ad0a.

Kind regards,
Verónica
